// See https://aka.ms/new-console-template for more information
using Gol;
using Spectre.Console;



using var cancellation = new CancellationTokenSource();
Console.CancelKeyPress += (s, e) =>
{
    cancellation.Cancel();
    e.Cancel = true;
};

var game = new Game(Seeds.S10x10);
var layout = new Layout("Root");
try
{
    AnsiConsole.Write(layout.Update(Align.Center(game.GetGrid(), VerticalAlignment.Middle)));
    AnsiConsole.WriteLine("Press any key to start");
    AnsiConsole.Console.Input.ReadKey(intercept: true);
    while (!cancellation.IsCancellationRequested)
    {
        await Task.Delay(1000, cancellation.Token);
        AnsiConsole.Clear();
        game.Tick();
        AnsiConsole.Write(layout.Update(Align.Center(game.GetGrid(), VerticalAlignment.Middle)));
    }
}
catch (TaskCanceledException)
{
    // Cancelled by user.
}

file static class Seeds
{
    public const string S10x10 = """
        ..........
        ....*.....
        ...***....
        ..........
        ..........
        ..........
        ..........
        ..........
        ..........
        ..........
        """;

    public const string S20x20 = """
        ....................
        ....................
        .....*****..........
        .....*...*..........
        .....*...*..........
        .....*...*..........
        .....*****..........
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        """;
}